### ISSUE TITLE
[Question] SolitudeSF/mpdclient

### ISSUE THREAD

**Issue by Miqueas** [treeform/nimdocs#4]
Why there's a 404 error for that repo?

**Comment by treeform** [comment]
SolitudeSF is not in the allow list:
```nim
allowedAuthorsList = @["treeform", "guzba", "nim-lang", "beef331"]
```

They would have to ask me to add them.

**Comment by Miqueas** [comment]
uh... i was thought that any repo is allowed bruh

**Comment by Miqueas** [comment]
anyway, thanks

**Comment by treeform** [comment]
Its opt in only.
